onlyflans/onlyflans/urls.py
from django.contrib import admin
from django.urls import path, include
from web.views import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls'))
    
    

]

onlyflans/web/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio),
    path('acerca/', views.acerca),
    path('bienvenido/', views.bienvenido),
    path('contacto/', views.contacto,name='contacto'),
    path('exito/', views.exito),
    path('logout/', views.cerrar_sesion, name ='logout'),
    path('login/',views.iniciar_sesion,name='login'),
    path('Flan/agregar/', views.crear_flan,name='agregarFlan'),
    path('flan/editar/',views.editar_flan,name='editarFlan')
]

onlyflans/web/models.py
from django.db import models
import uuid
# Create your models here.
class Flan(models.Model):
    flan_uuid = models.UUIDField()
    name = models.CharField( max_length=64)
    description= models.TextField()
    image_url = models.URLField()
    slug = models.SlugField()
    is_private = models.BooleanField()
    
    #atributos adicionales de fecha
    created_ad = models.DateTimeField(auto_now_add=True)
    updated_ad = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name 
    
class ContactForm(models.Model):
    contact_form_uuid = models.UUIDField(default = uuid.uuid4,editable = False) 
    customer_email = models.EmailField()
    customer_name = models.CharField( max_length=64)
    message = models.TextField()
    
     #atributos adicionales de fecha
    created_ad = models.DateTimeField(auto_now_add=True)
    updated_ad = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.customer_email 

onlyflans/web/forms.py
from django import forms

class ContactFormForm(forms.Form):
    customer_email = forms.EmailField(label = 'correo')
    customer_name = forms.CharField(max_length=64,label ='nombre')
    message = forms.CharField(label = 'Mensaje')
    
class FlanForm(forms.Form):
    flan_uuid = forms.UUIDField(label = 'uuid')
    name = forms.CharField( max_length=64,label='nombre')
    description= forms.CharField(label = 'Mensaje')
    image_url = forms.URLField(label = 'imagen')
    slug = forms.SlugField(label = 'slug')
    is_private = forms.BooleanField(label = 'privado',required=False)
    

onlyflans/web/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages


from .models import Flan,ContactForm
from .forms import ContactFormForm,FlanForm
# Create your views here.
def inicio(request):
    flanes_publicos = Flan.objects.filter(is_private=False)
    return render(request, 'index.html',{'datos':flanes_publicos} )

def acerca(request):
    return render(request, 'about.html')

@login_required
def bienvenido(request):
    
    flanes_privados = Flan.objects.filter(is_private=True)
    return render(request, 'welcome.html',{'datos':flanes_privados})


def exito(request):
    return render(request, 'exito.html')


def contacto(request):
    #validar metodo post
    if request.method == 'POST':
        form = ContactFormForm(request.POST)
        #validar información correcta
        if form.is_valid():
            #guardado de la información en la base de datos
            contact_form = ContactForm.objects.create(**form.cleaned_data)
            
            # redirección del metodo
            return HttpResponseRedirect('/exito')

    else: 
        # redirección del metodo
        form = ContactFormForm()
            
    return render(request,'contacto.html', {'form':form})

def cerrar_sesion(request):
    logout(request)
    messages.info(request,"sesión cerrada con éxito")
    return redirect('/')

def iniciar_sesion(request):
    if request.method == 'GET':
        return render(request,'registration/login.html')   
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'registration/login.html', {"error": "Usuario o password es incorrecto."})
        else:
            login(request, user)
            return redirect('/bienvenido')

@login_required         
def crear_flan(request):
    #validar metodo post
    if request.method == 'POST':
        form = FlanForm(request.POST)
        #print(request.POST)
        #validar información correcta
        if form.is_valid():
            #guardado de la información en la base de datos
            guardar_Flan = Flan.objects.create(**form.cleaned_data)
            # redirección del metodo
            messages.success(request,'Flan Agregado con Éxito')
            return redirect('/bienvenido')
    else: 
        # redirección del metodo
        form = FlanForm()
    return render(request,'crear_flan.html', {'form':form})


@login_required
def editar_flan(request):
    messages.error(request,'función en desarrollo, disculpes las molestias')
    return redirect('agregarFlan')

onlyflans/web/templates/about.html
{% extends "base.html" %}

{% block content %}

    
    <div class= "container">
        <h1 class="text-center">Nosotros</h1>
        <p style ="text-align: justify;">
                OnlyFlans es una empresa enfocada en el mundo de la
                pastelería y los postres, en especial en la venta de flan(de ahí
                su nombre), nace en 2021 en santiago de chile como una
                empresa familiar que pretende entregar productos de calidad
                a su clientela, estando ubicada en providencia, a pasos del
                metro Parque Bustamante.
        <p>
    </div>

    <div class= "container ">
            {% block 'carousel' %}
                {% include "carrusel.html" %}
            {% endblock  %}
    </div>

 
{% endblock  %}

onlyflans/web/templates/base.html
{% load static %}

<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#712cf9">
    <!-- jquery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!--Link css desde ubicación estatica-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>onlyflans</title>
  </head>
  <body>
    
    {% block 'svg' %}
    {% include 'svg.html' %}
    {% endblock %}

    <!-- BARRA NAVEGACION -->
    {% block 'header' %}
    {% include 'header.html' %}
    {% endblock %}

    <!-- MOSTRAR MENSAJE DE SESIÓN CERRADA-->
    {% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    {% endif %}



    {% block content %}
    {% endblock  %}

    <!-- FOOTER -->
    <div class="container-fluid">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="mb-3 mb-md-0 text-muted">desarrollado by Errante para Desafío
            Latam</span>
        </div>
    
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3"><a class="text-muted" href="https://twitter.com/" target="_blank"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="https://www.instagram.com" target="_blank"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="https://www.facebook.com" target="_blank"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
        </ul>
      </footer>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <script src="{% static 'js/script.js' %}"></script>
  </body>
  
</html>

onlyflans/web/templates/carrusel.html
{% load static %}

<div id="carouselExample" class="carousel slide">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'img/colun.png' %}" class="d-block w-100" alt="colun">
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/soprole.webp' %}" class="d-block w-100" alt="soprole">
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/nestlé.webp' %}" class="d-block w-100" alt="nestlé">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

onlyflans/web/templates/contacto.html
{% extends "base.html" %}

{% block content %}
    
    <div class= "container ">
        <h1 class="text-center">contacto</h1>
    </div>
    
    <div class ="container">
        <form action="{% url 'contacto' %}" method = "post">
            {%csrf_token%} 

                <div class="mb-3">
                    <label for="id_customer_email" class="form-label" >Correo:</label>
                    <input type="email" class="form-control" name="customer_email" maxlength="320" required="" id="id_customer_email">
                </div>
                <div class="mb-3">
                    <label for="id_customer_name" class="form-label" >Nombre:</label>
                    <input type="text" class="form-control" name="customer_name" maxlength="64" required="" id="id_customer_name">
                </div>
                <div class="mb-3">
                    <label for="id_message" class="form-label">Mensaje:</label>
                    <textarea type="text"class="form-control" name="message" required="" id="id_message" rows="4"></textarea>
                </div>
                <div class="d-grid gap-2  mx-auto">   
                    <input type="submit" class="btn btn-primary" value="submit">
                </div>
        </form>    
    </div>
{% endblock %}

onlyflans/web/templates/crear_flan.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5">
    <h2>Agregar Flan </h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_flan_uuid">UUID:</label>
            <input type="text" class="form-control" name="flan_uuid" required id="id_flan_uuid">
        </div>
        <div class="form-group">
            <label for="id_name">Nombre:</label>
            <input type="text" class="form-control" name="name" maxlength="64" required id="id_name">
        </div>
        <div class="form-group">
            <label for="id_description">Mensaje:</label>
            <input type="text" class="form-control" name="description" required id="id_description">
        </div>
        <div class="form-group">
            <label for="id_image_url">Imagen:</label>
            <input type="url" class="form-control" name="image_url" required id="id_image_url">
        </div>
        <div class="form-group">
            <label for="id_slug">Slug:</label>
            <input type="text" class="form-control" name="slug" required id="id_slug">
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" name="is_private"  id="id_is_private">
            <label class="form-check-label" for="id_is_private">Privado</label>
           
            
        </div>
        <button type="submit" class="btn btn-primary mt-3">Enviar</button>
    </form>
</div>
{% endblock  %}

onlyflans/web/templates/editar_flan.html
{% extends "base.html" %}

{% block content %}
<h1>Pagina en edición, disculpas las molestias</h1> 
{% endblock  %}

onlyflans/web/templates/exito.html
{% extends "base.html" %}
{% block content %}
<div class= "container text-center my-3 py-3">
    <h1 >Mensaje Enviado Con Éxito</h1>
    <h5 >¡Muchas Gracias!</h5>
    
        <a href="/">
            <button type="button" class="btn btn-primary btn-lg">Inicio</button>
        </a>
   
</div>
    

{% endblock  %}

onlyflans/web/templates/header.html
{% load static %} 
{% block 'header' %}

<header class="p-3 ">
    
   <!-- -------- BARRA DE NAVEGACION --------- -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary " >
      <div class="container-fluid">
            <a class="navbar-brand" href="/"><img class="img-logo" src="{% static 'img/OnlyFlans.png' %}" width=200> </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center navbar-css" id="navbarNav">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="/acerca">Nosotros</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="/bienvenido">Bienvenido</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="/contacto">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>

    </nav>
    {% block 'usuario_menu' %}
    {% include "menu_user.html" %}
    {% endblock  %}
</header> 

{% endblock  %}

onlyflans/web/templates/index.html
{% extends "base.html" %}

{% block content %}

    
        <div class= "container ">
            <h1 class="text-center">Inicio</h1>
        </div>

    
        <div class="card-group">
           
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
                
                    {% for flan in datos %}
                        <div class="col">
                            <div class="card" >
                                    <img src="{{flan.image_url}}" class="card-img-top img-card" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">{{flan.name}}</h5>
                                    <p class="card-text">{{flan.description}}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                
            </div>            
        </div>
  
{% endblock  %}

onlyflans/web/templates/menu_user.html
{% block 'usuario_menu' %}
<div class="container-fluid text-center py-2 bg-light-subtle justify-content-center usuario_menu">
    <!-- AUTENTICACION BOTONES -->

    {% if user.is_authenticated %}
    <a class="link-body-emphasis text-decoration-none icon-link-hover mx-2" style=" --bs-hover-color-rgb: 136, 151, 255;"><h4 id ="nombre_mostrar"> Bienvenido, {{user.first_name}} </h4></a>
        <div id ="menu" class="container-fluid" style="display:none">
            <!--style="display:none"-->
            <nav class="navbar navbar-expand-lg bbg-light-subtle" >
                <div class="container-fluid">
                  
                    <ul class="navbar-nav mx-auto">
                        {% if user.is_staff == 1  %}
                            <li class="nav-item">
                                <a class="icon-link icon-link-hover mx-2" style="--bs-link-hover-color-rgb: 136, 151, 255;" href="{% url 'agregarFlan' %}">Agregar Flan</a>
                            </li>
                            <li class="nav-item">
                                <a class="icon-link icon-link-hover mx-2" style="--bs-link-hover-color-rgb: 136, 151, 255;" href="{% url 'editarFlan' %}">Editar Flan</a>
                            </li>
                        {% endif %}
                            <li class="nav-item">
                                <a class="icon-link icon-link-hover" style="--bs-link-hover-color-rgb: 255, 6, 29;" href="{% url 'logout' %}">Cerrar Sesión</a>
                            </li>
    {% else %}
                            <li class="nav-item" style="list-style-type: none;"> 
                                <a class="icon-link icon-link-hover mx-2" style="--bs-link-hover-color-rgb: 136, 151, 255;" href="{% url 'login' %}">Iniciar Sesión</a>
                            </li>  
    {% endif %}  
                    </ul>
                </div>
          </nav>
        </div>
</div>
{% endblock  %}

onlyflans/web/templates/svg.html
{% block 'svg' %}
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        
      <symbol id="facebook" viewBox="0 0 16 16">
        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
      </symbol>
      <symbol id="instagram" viewBox="0 0 16 16">
          <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
      </symbol>
      <symbol id="twitter" viewBox="0 0 16 16">
        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
      </symbol>
    </svg>

  {% endblock  %}

onlyflans/web/templates/welcome.html
{% extends "base.html" %}

{% block content %}

        <div class= "container ">
            <h1 class="text-center">Bienvenido</h1>
        </div>

    <div class="card-group">
       <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            
                {% for flan in datos %}
                    <div class="col">
                        <div class="card" >
                                <img src="{{flan.image_url}}" class="card-img-top img-card" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{flan.name}}</h5>
                                <p class="card-text">{{flan.description}}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            
        </div>            
    </div>




{% endblock  %}